### ISSUE TITLE
[Link] 岛风

### ISSUE THREAD

**Issue by AgxCOy** [AgxCOy/AgxCOy#5]
```yaml blog-link
# 名称 Your Name
name: Shimakaze 岛风
# 头像 Your Avatar URI
icon: https://blog.shimakaze.dev/avatar.webp
# 自述、留言 Your Note 
desc: Yes, PowerShell! Yes, .NET!
# 链接 Your Website URI
link: https://blog.shimakaze.dev
```
